sudo: required
dist: trusty
language: cpp
compiler:
- clang
- g++
before_install:
- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"
- if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        packages:
        - g++-4.8
        - clang++-3.8
env: COMPILER=clang++3.8
script:
    make
